<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Pubsmith.Core\Pubsmith.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenMcdf" Version="3.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pubsmith.PubReader.Tests" />
  </ItemGroup>

</Project>
