<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\fixtures\pub\picture__base.pub;..\fixtures\pub\text__base.pub" LinkBase="fixtures\pub" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pubsmith.Cli\Pubsmith.Cli.csproj" />
    <ProjectReference Include="..\..\src\Pubsmith.Rendering\Pubsmith.Rendering.csproj" />
    <ProjectReference Include="..\..\src\Pubsmith.Core\Pubsmith.Core.csproj" />
  </ItemGroup>

</Project>